spring:
  application:
    name: authentication-management
  datasource:
    url: jdbc:postgresql://localhost:5432/usersDB
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format-sql: true
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9234

logging:
  level:
    org:
      hibernate:
        type: trace